apiVersion: apps/v1
kind: Deployment
metadata:
  name: oasis-deployment
  namespace: oasis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oasis
  template:
    metadata:
      labels:
        app: oasis
    spec:
      containers:
      - name: oasis
        image: ghcr.io/oasis/oasis:main
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
        - name: OLLAMA_BASE_URL
          value: "http://ollama-service.oasis.svc.cluster.local:11434"
        tty: true
        volumeMounts:
        - name: webui-volume
          mountPath: /app/backend/data
      volumes:
      - name: webui-volume
        persistentVolumeClaim:
          claimName: oasis-pvc          